{% set name = "bmi_era5" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 300e449ce8f0093914db166403b3d295f4e20dfb350f8b1c8fc2a42587a010db


build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bmipy
    - netcdf4
    - numpy
    - pyyaml
    - requests
    - xarray
    - cftime
    - cdsapi >=0.7.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - bmi_era5

about:
  home: https://github.com/gantian127/bmi_era5
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: |
    A Python library as a Basic Model Interface implementation for the ERA5 data
  description: |
    bmi_era5 package is an implementation of the Basic Model Interface (BMI) for 
    the ERA5 dataset. This package uses the CDS API to download the ERA5 dataset 
    and wraps the dataset with BMI for data control and query (currently support 3-dimensional ERA5 dataset).
    This package is not implemented for people to use but is the key element to 
    convert the ERA5 dataset into a data component (pymt_era5) for the PyMT modeling 
    framework developed by Community Surface Dynamics Modeling System (CSDMS).
  doc_url: https://bmi-era5.readthedocs.io/
  dev_url: https://github.com/gantian127/bmi_era5

extra:
  recipe-maintainers:
    - gantian127
